version: 1.0.{build}
skip_non_tags: true
build_script:
- ps: >-
    $source = "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-x86_64.exe"

    $destination = "Miniconda3-latest-Windows-x86_64.exe"

    Invoke-WebRequest $source -OutFile $destination

    $conda = "C:\temp\miniconda3"

    $args = "/InstallationType=JustMe /RegisterPython=0 /S /D=$conda"

    Start-Process -FilePath $destination -ArgumentList $args -Wait -Passthru

    Start-Process $conda\Scripts\conda.exe -ArgumentList "install -y constructor=1.5" -Wait

    cd c:\projects\r-jupyter-notebook

    $ver = git describe --tags

    Add-Content .\construct.yaml "version: $ver"

    Start-Process $conda\Scripts\constructor.exe -ArgumentList "." -Wait -RedirectStandardOutput stdout.txt -RedirectStandardError stderr.txt

    Get-Content stdout.txt

    Get-Content stderr.txt

    dir

    Update-AppveyorBuild -Version "$ver"
artifacts:
- path: r-jupyter-*.exe
  name: installer
deploy:
- provider: GitHub
  auth_token:
    secure: 7ravZMzSffrGxazluk9GPSeqSFJLT61C5o8KGqOjlj5Z66uV0+49T2QO+kM5Xiji
  artifact: installer
